Description: >
  Devops project

Parameters:
  ID:
    Type: String
  EKSName:
    Description: Unique identifier.
    Type: String
    Default: devops-proj
  EKSRoleArn:
    Type: String
    Default: arn:aws:iam::432737993985:role/myEksClusterRole
  EKSNodeGroupRoleArn:
    Type: String
    Default: arn:aws:iam::432737993985:role/myEKSWorkerNodeRole

Resources:
  EKSClusterInstances:
    Type: AWS::EKS::Cluster
    Properties:
      KubernetesNetworkConfig:
        IpFamily: ipv4
      Name: !Ref EKSName
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0695b766b7f33c95e
          - subnet-010aaabf0d1a14e8b
          - subnet-098ad8c4b2da8786f
      RoleArn: !Ref EKSRoleArn
      Tags:
        - Key: Name
          Value: !Sub ${EKSName}
      Version: 1.27
  EKSClusterNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
      ClusterName: !Ref EKSClusterInstances
      DiskSize: 20
      InstanceTypes:
        - t3.medium
      NodegroupName: !Sub ${EKSName}-${ID}
      NodeRole: !Ref EKSNodeGroupRoleArn
      Subnets:
        - subnet-0695b766b7f33c95e
        - subnet-010aaabf0d1a14e8b
        - subnet-098ad8c4b2da8786f
      Tags:
        Name: !Sub ${EKSName}-eks-ng
