Description: >
  Devops project

Parameters:
  ID:
    Type: String
  EKSName:
    Description: Unique identifier.
    Type: String
    Default: devops-proj
  EKSRoleArn:
    Type: String
    Default: arn:aws:iam::432737993985:role/myEKSClusterRole
  EKSNodeGroupRoleArn:
    Type: String
    Default: arn:aws:iam::432737993985:role/myEKSWorkerNodeRole

Resources:
  EKSClusterInstances:
    Type: AWS::EKS::Cluster
    Properties:
      KubernetesNetworkConfig:
        IpFamily: ipv4
      Name: !Ref EKSName
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-09d1bf4819361643e
          - subnet-0693f59a0d958a86c
          - subnet-061e3dc3c236394ee
      RoleArn: !Ref EKSRoleArn
      Tags:
        - Key: Name
          Value: !Sub ${EKSName}
      Version: 1.27
  EKSClusterNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
      ClusterName: !Ref EKSClusterInstances
      DiskSize: 20
      InstanceTypes:
        - t3.medium
      NodegroupName: !Sub ${EKSName}-${ID}
      NodeRole: !Ref EKSNodeGroupRoleArn
      Subnets:
        - subnet-09d1bf4819361643e
        - subnet-0693f59a0d958a86c
        - subnet-061e3dc3c236394ee
      Tags:
        Name: !Sub ${EKSName}-eks-ng
